// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: bots.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bots_GetAssistantBots_FullMethodName   = "/Bots/GetAssistantBots"
	Bots_AddAssistantBot_FullMethodName    = "/Bots/AddAssistantBot"
	Bots_DeleteAssistantBot_FullMethodName = "/Bots/DeleteAssistantBot"
	Bots_UpdateAssistantBot_FullMethodName = "/Bots/UpdateAssistantBot"
	Bots_SendMessage_FullMethodName        = "/Bots/SendMessage"
)

// BotsClient is the client API for Bots service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BotsClient interface {
	GetAssistantBots(ctx context.Context, in *GetAssistantBotsRequest, opts ...grpc.CallOption) (*GetAssistantBotsResponse, error)
	AddAssistantBot(ctx context.Context, in *AddAssistantBotRequest, opts ...grpc.CallOption) (*AddAssistantBotResponse, error)
	DeleteAssistantBot(ctx context.Context, in *DeleteAssistantBotRequest, opts ...grpc.CallOption) (*DeleteAssistantBotResponse, error)
	UpdateAssistantBot(ctx context.Context, in *UpdateAssistantBotRequest, opts ...grpc.CallOption) (*UpdateAssistantBotResponse, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
}

type botsClient struct {
	cc grpc.ClientConnInterface
}

func NewBotsClient(cc grpc.ClientConnInterface) BotsClient {
	return &botsClient{cc}
}

func (c *botsClient) GetAssistantBots(ctx context.Context, in *GetAssistantBotsRequest, opts ...grpc.CallOption) (*GetAssistantBotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssistantBotsResponse)
	err := c.cc.Invoke(ctx, Bots_GetAssistantBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botsClient) AddAssistantBot(ctx context.Context, in *AddAssistantBotRequest, opts ...grpc.CallOption) (*AddAssistantBotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAssistantBotResponse)
	err := c.cc.Invoke(ctx, Bots_AddAssistantBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botsClient) DeleteAssistantBot(ctx context.Context, in *DeleteAssistantBotRequest, opts ...grpc.CallOption) (*DeleteAssistantBotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAssistantBotResponse)
	err := c.cc.Invoke(ctx, Bots_DeleteAssistantBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botsClient) UpdateAssistantBot(ctx context.Context, in *UpdateAssistantBotRequest, opts ...grpc.CallOption) (*UpdateAssistantBotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAssistantBotResponse)
	err := c.cc.Invoke(ctx, Bots_UpdateAssistantBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botsClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, Bots_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotsServer is the server API for Bots service.
// All implementations must embed UnimplementedBotsServer
// for forward compatibility.
type BotsServer interface {
	GetAssistantBots(context.Context, *GetAssistantBotsRequest) (*GetAssistantBotsResponse, error)
	AddAssistantBot(context.Context, *AddAssistantBotRequest) (*AddAssistantBotResponse, error)
	DeleteAssistantBot(context.Context, *DeleteAssistantBotRequest) (*DeleteAssistantBotResponse, error)
	UpdateAssistantBot(context.Context, *UpdateAssistantBotRequest) (*UpdateAssistantBotResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	mustEmbedUnimplementedBotsServer()
}

// UnimplementedBotsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBotsServer struct{}

func (UnimplementedBotsServer) GetAssistantBots(context.Context, *GetAssistantBotsRequest) (*GetAssistantBotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssistantBots not implemented")
}
func (UnimplementedBotsServer) AddAssistantBot(context.Context, *AddAssistantBotRequest) (*AddAssistantBotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAssistantBot not implemented")
}
func (UnimplementedBotsServer) DeleteAssistantBot(context.Context, *DeleteAssistantBotRequest) (*DeleteAssistantBotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAssistantBot not implemented")
}
func (UnimplementedBotsServer) UpdateAssistantBot(context.Context, *UpdateAssistantBotRequest) (*UpdateAssistantBotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAssistantBot not implemented")
}
func (UnimplementedBotsServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedBotsServer) mustEmbedUnimplementedBotsServer() {}
func (UnimplementedBotsServer) testEmbeddedByValue()              {}

// UnsafeBotsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotsServer will
// result in compilation errors.
type UnsafeBotsServer interface {
	mustEmbedUnimplementedBotsServer()
}

func RegisterBotsServer(s grpc.ServiceRegistrar, srv BotsServer) {
	// If the following call pancis, it indicates UnimplementedBotsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bots_ServiceDesc, srv)
}

func _Bots_GetAssistantBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssistantBotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotsServer).GetAssistantBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bots_GetAssistantBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotsServer).GetAssistantBots(ctx, req.(*GetAssistantBotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bots_AddAssistantBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAssistantBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotsServer).AddAssistantBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bots_AddAssistantBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotsServer).AddAssistantBot(ctx, req.(*AddAssistantBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bots_DeleteAssistantBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAssistantBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotsServer).DeleteAssistantBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bots_DeleteAssistantBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotsServer).DeleteAssistantBot(ctx, req.(*DeleteAssistantBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bots_UpdateAssistantBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssistantBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotsServer).UpdateAssistantBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bots_UpdateAssistantBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotsServer).UpdateAssistantBot(ctx, req.(*UpdateAssistantBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bots_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotsServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bots_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotsServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Bots_ServiceDesc is the grpc.ServiceDesc for Bots service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bots_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Bots",
	HandlerType: (*BotsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAssistantBots",
			Handler:    _Bots_GetAssistantBots_Handler,
		},
		{
			MethodName: "AddAssistantBot",
			Handler:    _Bots_AddAssistantBot_Handler,
		},
		{
			MethodName: "DeleteAssistantBot",
			Handler:    _Bots_DeleteAssistantBot_Handler,
		},
		{
			MethodName: "UpdateAssistantBot",
			Handler:    _Bots_UpdateAssistantBot_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Bots_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bots.proto",
}
