// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.1
// source: bots.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssistantBot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	AssistantId   int64                  `protobuf:"varint,2,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=Platform,proto3" json:"Platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantBot) Reset() {
	*x = AssistantBot{}
	mi := &file_bots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantBot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantBot) ProtoMessage() {}

func (x *AssistantBot) ProtoReflect() protoreflect.Message {
	mi := &file_bots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantBot.ProtoReflect.Descriptor instead.
func (*AssistantBot) Descriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{0}
}

func (x *AssistantBot) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AssistantBot) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *AssistantBot) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type GetAssistantBotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int64                  `protobuf:"varint,1,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssistantBotsRequest) Reset() {
	*x = GetAssistantBotsRequest{}
	mi := &file_bots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssistantBotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssistantBotsRequest) ProtoMessage() {}

func (x *GetAssistantBotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssistantBotsRequest.ProtoReflect.Descriptor instead.
func (*GetAssistantBotsRequest) Descriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{1}
}

func (x *GetAssistantBotsRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

type GetAssistantBotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bots          []*AssistantBot        `protobuf:"bytes,1,rep,name=Bots,proto3" json:"Bots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssistantBotsResponse) Reset() {
	*x = GetAssistantBotsResponse{}
	mi := &file_bots_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssistantBotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssistantBotsResponse) ProtoMessage() {}

func (x *GetAssistantBotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bots_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssistantBotsResponse.ProtoReflect.Descriptor instead.
func (*GetAssistantBotsResponse) Descriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{2}
}

func (x *GetAssistantBotsResponse) GetBots() []*AssistantBot {
	if x != nil {
		return x.Bots
	}
	return nil
}

type AddAssistantBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int64                  `protobuf:"varint,1,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=Platform,proto3" json:"Platform,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAssistantBotRequest) Reset() {
	*x = AddAssistantBotRequest{}
	mi := &file_bots_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAssistantBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAssistantBotRequest) ProtoMessage() {}

func (x *AddAssistantBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bots_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAssistantBotRequest.ProtoReflect.Descriptor instead.
func (*AddAssistantBotRequest) Descriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{3}
}

func (x *AddAssistantBotRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *AddAssistantBotRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AddAssistantBotRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AddAssistantBotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAssistantBotResponse) Reset() {
	*x = AddAssistantBotResponse{}
	mi := &file_bots_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAssistantBotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAssistantBotResponse) ProtoMessage() {}

func (x *AddAssistantBotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bots_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAssistantBotResponse.ProtoReflect.Descriptor instead.
func (*AddAssistantBotResponse) Descriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{4}
}

func (x *AddAssistantBotResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAssistantBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         int64                  `protobuf:"varint,1,opt,name=BotId,proto3" json:"BotId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssistantBotRequest) Reset() {
	*x = DeleteAssistantBotRequest{}
	mi := &file_bots_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssistantBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssistantBotRequest) ProtoMessage() {}

func (x *DeleteAssistantBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bots_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssistantBotRequest.ProtoReflect.Descriptor instead.
func (*DeleteAssistantBotRequest) Descriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAssistantBotRequest) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

type DeleteAssistantBotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssistantBotResponse) Reset() {
	*x = DeleteAssistantBotResponse{}
	mi := &file_bots_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssistantBotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssistantBotResponse) ProtoMessage() {}

func (x *DeleteAssistantBotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bots_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssistantBotResponse.ProtoReflect.Descriptor instead.
func (*DeleteAssistantBotResponse) Descriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAssistantBotResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateAssistantBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int64                  `protobuf:"varint,1,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=Platform,proto3" json:"Platform,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssistantBotRequest) Reset() {
	*x = UpdateAssistantBotRequest{}
	mi := &file_bots_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssistantBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssistantBotRequest) ProtoMessage() {}

func (x *UpdateAssistantBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bots_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssistantBotRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssistantBotRequest) Descriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAssistantBotRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *UpdateAssistantBotRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UpdateAssistantBotRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UpdateAssistantBotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotId         int64                  `protobuf:"varint,1,opt,name=BotId,proto3" json:"BotId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssistantBotResponse) Reset() {
	*x = UpdateAssistantBotResponse{}
	mi := &file_bots_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssistantBotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssistantBotResponse) ProtoMessage() {}

func (x *UpdateAssistantBotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bots_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssistantBotResponse.ProtoReflect.Descriptor instead.
func (*UpdateAssistantBotResponse) Descriptor() ([]byte, []int) {
	return file_bots_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAssistantBotResponse) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

var File_bots_proto protoreflect.FileDescriptor

const file_bots_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"bots.proto\"\\\n" +
	"\fAssistantBot\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12 \n" +
	"\vAssistantId\x18\x02 \x01(\x03R\vAssistantId\x12\x1a\n" +
	"\bPlatform\x18\x03 \x01(\tR\bPlatform\";\n" +
	"\x17GetAssistantBotsRequest\x12 \n" +
	"\vAssistantId\x18\x01 \x01(\x03R\vAssistantId\"=\n" +
	"\x18GetAssistantBotsResponse\x12!\n" +
	"\x04Bots\x18\x01 \x03(\v2\r.AssistantBotR\x04Bots\"l\n" +
	"\x16AddAssistantBotRequest\x12 \n" +
	"\vAssistantId\x18\x01 \x01(\x03R\vAssistantId\x12\x1a\n" +
	"\bPlatform\x18\x02 \x01(\tR\bPlatform\x12\x14\n" +
	"\x05Token\x18\x03 \x01(\tR\x05Token\")\n" +
	"\x17AddAssistantBotResponse\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"1\n" +
	"\x19DeleteAssistantBotRequest\x12\x14\n" +
	"\x05BotId\x18\x01 \x01(\x03R\x05BotId\"4\n" +
	"\x1aDeleteAssistantBotResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\"o\n" +
	"\x19UpdateAssistantBotRequest\x12 \n" +
	"\vAssistantId\x18\x01 \x01(\x03R\vAssistantId\x12\x1a\n" +
	"\bPlatform\x18\x02 \x01(\tR\bPlatform\x12\x14\n" +
	"\x05Token\x18\x03 \x01(\tR\x05Token\"2\n" +
	"\x1aUpdateAssistantBotResponse\x12\x14\n" +
	"\x05BotId\x18\x01 \x01(\x03R\x05BotId2\xb3\x02\n" +
	"\x04Bots\x12G\n" +
	"\x10GetAssistantBots\x12\x18.GetAssistantBotsRequest\x1a\x19.GetAssistantBotsResponse\x12D\n" +
	"\x0fAddAssistantBot\x12\x17.AddAssistantBotRequest\x1a\x18.AddAssistantBotResponse\x12M\n" +
	"\x12DeleteAssistantBot\x12\x1a.DeleteAssistantBotRequest\x1a\x1b.DeleteAssistantBotResponse\x12M\n" +
	"\x12UpdateAssistantBot\x12\x1a.UpdateAssistantBotRequest\x1a\x1b.UpdateAssistantBotResponseB\tZ\a.;protob\x06proto3"

var (
	file_bots_proto_rawDescOnce sync.Once
	file_bots_proto_rawDescData []byte
)

func file_bots_proto_rawDescGZIP() []byte {
	file_bots_proto_rawDescOnce.Do(func() {
		file_bots_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bots_proto_rawDesc), len(file_bots_proto_rawDesc)))
	})
	return file_bots_proto_rawDescData
}

var file_bots_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bots_proto_goTypes = []any{
	(*AssistantBot)(nil),               // 0: AssistantBot
	(*GetAssistantBotsRequest)(nil),    // 1: GetAssistantBotsRequest
	(*GetAssistantBotsResponse)(nil),   // 2: GetAssistantBotsResponse
	(*AddAssistantBotRequest)(nil),     // 3: AddAssistantBotRequest
	(*AddAssistantBotResponse)(nil),    // 4: AddAssistantBotResponse
	(*DeleteAssistantBotRequest)(nil),  // 5: DeleteAssistantBotRequest
	(*DeleteAssistantBotResponse)(nil), // 6: DeleteAssistantBotResponse
	(*UpdateAssistantBotRequest)(nil),  // 7: UpdateAssistantBotRequest
	(*UpdateAssistantBotResponse)(nil), // 8: UpdateAssistantBotResponse
}
var file_bots_proto_depIdxs = []int32{
	0, // 0: GetAssistantBotsResponse.Bots:type_name -> AssistantBot
	1, // 1: Bots.GetAssistantBots:input_type -> GetAssistantBotsRequest
	3, // 2: Bots.AddAssistantBot:input_type -> AddAssistantBotRequest
	5, // 3: Bots.DeleteAssistantBot:input_type -> DeleteAssistantBotRequest
	7, // 4: Bots.UpdateAssistantBot:input_type -> UpdateAssistantBotRequest
	2, // 5: Bots.GetAssistantBots:output_type -> GetAssistantBotsResponse
	4, // 6: Bots.AddAssistantBot:output_type -> AddAssistantBotResponse
	6, // 7: Bots.DeleteAssistantBot:output_type -> DeleteAssistantBotResponse
	8, // 8: Bots.UpdateAssistantBot:output_type -> UpdateAssistantBotResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bots_proto_init() }
func file_bots_proto_init() {
	if File_bots_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bots_proto_rawDesc), len(file_bots_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bots_proto_goTypes,
		DependencyIndexes: file_bots_proto_depIdxs,
		MessageInfos:      file_bots_proto_msgTypes,
	}.Build()
	File_bots_proto = out.File
	file_bots_proto_goTypes = nil
	file_bots_proto_depIdxs = nil
}
