// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: clients.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Clients_CreateAssistant_FullMethodName       = "/Clients/CreateAssistant"
	Clients_AddDocument_FullMethodName           = "/Clients/AddDocument"
	Clients_DeleteAssistant_FullMethodName       = "/Clients/DeleteAssistant"
	Clients_DeleteDocument_FullMethodName        = "/Clients/DeleteDocument"
	Clients_GetOneAssistant_FullMethodName       = "/Clients/GetOneAssistant"
	Clients_GetUserAssistants_FullMethodName     = "/Clients/GetUserAssistants"
	Clients_GetAssistantDocuments_FullMethodName = "/Clients/GetAssistantDocuments"
)

// ClientsClient is the client API for Clients service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientsClient interface {
	CreateAssistant(ctx context.Context, in *CreateAssistantRequest, opts ...grpc.CallOption) (*CreateAssistantResponse, error)
	AddDocument(ctx context.Context, in *AddDocumentRequest, opts ...grpc.CallOption) (*AddDocumentResponse, error)
	DeleteAssistant(ctx context.Context, in *DeleteAssistantRequest, opts ...grpc.CallOption) (*DeleteAssistantResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	GetOneAssistant(ctx context.Context, in *GetOneAssistantRequest, opts ...grpc.CallOption) (*GetOneAssistantResponse, error)
	GetUserAssistants(ctx context.Context, in *GetUserAssistantsRequest, opts ...grpc.CallOption) (*GetUserAssistantsResponse, error)
	GetAssistantDocuments(ctx context.Context, in *GetAssistantDocumentsRequest, opts ...grpc.CallOption) (*GetAssistantDocumentsResponse, error)
}

type clientsClient struct {
	cc grpc.ClientConnInterface
}

func NewClientsClient(cc grpc.ClientConnInterface) ClientsClient {
	return &clientsClient{cc}
}

func (c *clientsClient) CreateAssistant(ctx context.Context, in *CreateAssistantRequest, opts ...grpc.CallOption) (*CreateAssistantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAssistantResponse)
	err := c.cc.Invoke(ctx, Clients_CreateAssistant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) AddDocument(ctx context.Context, in *AddDocumentRequest, opts ...grpc.CallOption) (*AddDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDocumentResponse)
	err := c.cc.Invoke(ctx, Clients_AddDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) DeleteAssistant(ctx context.Context, in *DeleteAssistantRequest, opts ...grpc.CallOption) (*DeleteAssistantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAssistantResponse)
	err := c.cc.Invoke(ctx, Clients_DeleteAssistant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDocumentResponse)
	err := c.cc.Invoke(ctx, Clients_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) GetOneAssistant(ctx context.Context, in *GetOneAssistantRequest, opts ...grpc.CallOption) (*GetOneAssistantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOneAssistantResponse)
	err := c.cc.Invoke(ctx, Clients_GetOneAssistant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) GetUserAssistants(ctx context.Context, in *GetUserAssistantsRequest, opts ...grpc.CallOption) (*GetUserAssistantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAssistantsResponse)
	err := c.cc.Invoke(ctx, Clients_GetUserAssistants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) GetAssistantDocuments(ctx context.Context, in *GetAssistantDocumentsRequest, opts ...grpc.CallOption) (*GetAssistantDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssistantDocumentsResponse)
	err := c.cc.Invoke(ctx, Clients_GetAssistantDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientsServer is the server API for Clients service.
// All implementations must embed UnimplementedClientsServer
// for forward compatibility.
type ClientsServer interface {
	CreateAssistant(context.Context, *CreateAssistantRequest) (*CreateAssistantResponse, error)
	AddDocument(context.Context, *AddDocumentRequest) (*AddDocumentResponse, error)
	DeleteAssistant(context.Context, *DeleteAssistantRequest) (*DeleteAssistantResponse, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	GetOneAssistant(context.Context, *GetOneAssistantRequest) (*GetOneAssistantResponse, error)
	GetUserAssistants(context.Context, *GetUserAssistantsRequest) (*GetUserAssistantsResponse, error)
	GetAssistantDocuments(context.Context, *GetAssistantDocumentsRequest) (*GetAssistantDocumentsResponse, error)
	mustEmbedUnimplementedClientsServer()
}

// UnimplementedClientsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientsServer struct{}

func (UnimplementedClientsServer) CreateAssistant(context.Context, *CreateAssistantRequest) (*CreateAssistantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAssistant not implemented")
}
func (UnimplementedClientsServer) AddDocument(context.Context, *AddDocumentRequest) (*AddDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDocument not implemented")
}
func (UnimplementedClientsServer) DeleteAssistant(context.Context, *DeleteAssistantRequest) (*DeleteAssistantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAssistant not implemented")
}
func (UnimplementedClientsServer) DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedClientsServer) GetOneAssistant(context.Context, *GetOneAssistantRequest) (*GetOneAssistantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOneAssistant not implemented")
}
func (UnimplementedClientsServer) GetUserAssistants(context.Context, *GetUserAssistantsRequest) (*GetUserAssistantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAssistants not implemented")
}
func (UnimplementedClientsServer) GetAssistantDocuments(context.Context, *GetAssistantDocumentsRequest) (*GetAssistantDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssistantDocuments not implemented")
}
func (UnimplementedClientsServer) mustEmbedUnimplementedClientsServer() {}
func (UnimplementedClientsServer) testEmbeddedByValue()                 {}

// UnsafeClientsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientsServer will
// result in compilation errors.
type UnsafeClientsServer interface {
	mustEmbedUnimplementedClientsServer()
}

func RegisterClientsServer(s grpc.ServiceRegistrar, srv ClientsServer) {
	// If the following call pancis, it indicates UnimplementedClientsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Clients_ServiceDesc, srv)
}

func _Clients_CreateAssistant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssistantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).CreateAssistant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_CreateAssistant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).CreateAssistant(ctx, req.(*CreateAssistantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_AddDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).AddDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_AddDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).AddDocument(ctx, req.(*AddDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_DeleteAssistant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAssistantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).DeleteAssistant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_DeleteAssistant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).DeleteAssistant(ctx, req.(*DeleteAssistantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_GetOneAssistant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneAssistantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).GetOneAssistant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_GetOneAssistant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).GetOneAssistant(ctx, req.(*GetOneAssistantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_GetUserAssistants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAssistantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).GetUserAssistants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_GetUserAssistants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).GetUserAssistants(ctx, req.(*GetUserAssistantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_GetAssistantDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssistantDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).GetAssistantDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_GetAssistantDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).GetAssistantDocuments(ctx, req.(*GetAssistantDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Clients_ServiceDesc is the grpc.ServiceDesc for Clients service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Clients_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Clients",
	HandlerType: (*ClientsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAssistant",
			Handler:    _Clients_CreateAssistant_Handler,
		},
		{
			MethodName: "AddDocument",
			Handler:    _Clients_AddDocument_Handler,
		},
		{
			MethodName: "DeleteAssistant",
			Handler:    _Clients_DeleteAssistant_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _Clients_DeleteDocument_Handler,
		},
		{
			MethodName: "GetOneAssistant",
			Handler:    _Clients_GetOneAssistant_Handler,
		},
		{
			MethodName: "GetUserAssistants",
			Handler:    _Clients_GetUserAssistants_Handler,
		},
		{
			MethodName: "GetAssistantDocuments",
			Handler:    _Clients_GetAssistantDocuments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clients.proto",
}
