// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.1
// source: clients.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Assistant struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId             int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Tag                string                 `protobuf:"bytes,4,opt,name=Tag,proto3" json:"Tag,omitempty"`
	FirstMessage       string                 `protobuf:"bytes,5,opt,name=FirstMessage,proto3" json:"FirstMessage,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	TelegramBotExists  bool                   `protobuf:"varint,7,opt,name=TelegramBotExists,proto3" json:"TelegramBotExists,omitempty"`
	TodayQuestions     int64                  `protobuf:"varint,8,opt,name=TodayQuestions,proto3" json:"TodayQuestions,omitempty"`
	ThisMonthQuestions int64                  `protobuf:"varint,9,opt,name=ThisMonthQuestions,proto3" json:"ThisMonthQuestions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Assistant) Reset() {
	*x = Assistant{}
	mi := &file_clients_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assistant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assistant) ProtoMessage() {}

func (x *Assistant) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assistant.ProtoReflect.Descriptor instead.
func (*Assistant) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{0}
}

func (x *Assistant) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Assistant) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Assistant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Assistant) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Assistant) GetFirstMessage() string {
	if x != nil {
		return x.FirstMessage
	}
	return ""
}

func (x *Assistant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Assistant) GetTelegramBotExists() bool {
	if x != nil {
		return x.TelegramBotExists
	}
	return false
}

func (x *Assistant) GetTodayQuestions() int64 {
	if x != nil {
		return x.TodayQuestions
	}
	return 0
}

func (x *Assistant) GetThisMonthQuestions() int64 {
	if x != nil {
		return x.ThisMonthQuestions
	}
	return 0
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	AssistantId   int64                  `protobuf:"varint,2,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=FileName,proto3" json:"FileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_clients_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Document) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *Document) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type CreateAssistantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=Tag,proto3" json:"Tag,omitempty"`
	FirstMessage  string                 `protobuf:"bytes,4,opt,name=FirstMessage,proto3" json:"FirstMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssistantRequest) Reset() {
	*x = CreateAssistantRequest{}
	mi := &file_clients_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssistantRequest) ProtoMessage() {}

func (x *CreateAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssistantRequest.ProtoReflect.Descriptor instead.
func (*CreateAssistantRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAssistantRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateAssistantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAssistantRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *CreateAssistantRequest) GetFirstMessage() string {
	if x != nil {
		return x.FirstMessage
	}
	return ""
}

type CreateAssistantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int64                  `protobuf:"varint,1,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssistantResponse) Reset() {
	*x = CreateAssistantResponse{}
	mi := &file_clients_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssistantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssistantResponse) ProtoMessage() {}

func (x *CreateAssistantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssistantResponse.ProtoReflect.Descriptor instead.
func (*CreateAssistantResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAssistantResponse) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

type AddDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int64                  `protobuf:"varint,1,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=FileName,proto3" json:"FileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDocumentRequest) Reset() {
	*x = AddDocumentRequest{}
	mi := &file_clients_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDocumentRequest) ProtoMessage() {}

func (x *AddDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDocumentRequest.ProtoReflect.Descriptor instead.
func (*AddDocumentRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{4}
}

func (x *AddDocumentRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *AddDocumentRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type AddDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    int64                  `protobuf:"varint,1,opt,name=DocumentId,proto3" json:"DocumentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDocumentResponse) Reset() {
	*x = AddDocumentResponse{}
	mi := &file_clients_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDocumentResponse) ProtoMessage() {}

func (x *AddDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDocumentResponse.ProtoReflect.Descriptor instead.
func (*AddDocumentResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{5}
}

func (x *AddDocumentResponse) GetDocumentId() int64 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

type DeleteAssistantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int64                  `protobuf:"varint,1,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssistantRequest) Reset() {
	*x = DeleteAssistantRequest{}
	mi := &file_clients_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssistantRequest) ProtoMessage() {}

func (x *DeleteAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssistantRequest.ProtoReflect.Descriptor instead.
func (*DeleteAssistantRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAssistantRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *DeleteAssistantRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteAssistantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssistantResponse) Reset() {
	*x = DeleteAssistantResponse{}
	mi := &file_clients_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssistantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssistantResponse) ProtoMessage() {}

func (x *DeleteAssistantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssistantResponse.ProtoReflect.Descriptor instead.
func (*DeleteAssistantResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAssistantResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    int64                  `protobuf:"varint,1,opt,name=DocumentId,proto3" json:"DocumentId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_clients_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDocumentRequest) GetDocumentId() int64 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

func (x *DeleteDocumentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_clients_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDocumentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetOneAssistantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int64                  `protobuf:"varint,1,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	AssistantTag  int64                  `protobuf:"varint,2,opt,name=AssistantTag,proto3" json:"AssistantTag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneAssistantRequest) Reset() {
	*x = GetOneAssistantRequest{}
	mi := &file_clients_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneAssistantRequest) ProtoMessage() {}

func (x *GetOneAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneAssistantRequest.ProtoReflect.Descriptor instead.
func (*GetOneAssistantRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{10}
}

func (x *GetOneAssistantRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *GetOneAssistantRequest) GetAssistantTag() int64 {
	if x != nil {
		return x.AssistantTag
	}
	return 0
}

type GetOneAssistantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assistant     *Assistant             `protobuf:"bytes,1,opt,name=Assistant,proto3" json:"Assistant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneAssistantResponse) Reset() {
	*x = GetOneAssistantResponse{}
	mi := &file_clients_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneAssistantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneAssistantResponse) ProtoMessage() {}

func (x *GetOneAssistantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneAssistantResponse.ProtoReflect.Descriptor instead.
func (*GetOneAssistantResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{11}
}

func (x *GetOneAssistantResponse) GetAssistant() *Assistant {
	if x != nil {
		return x.Assistant
	}
	return nil
}

type GetUserAssistantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAssistantsRequest) Reset() {
	*x = GetUserAssistantsRequest{}
	mi := &file_clients_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAssistantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAssistantsRequest) ProtoMessage() {}

func (x *GetUserAssistantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAssistantsRequest.ProtoReflect.Descriptor instead.
func (*GetUserAssistantsRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserAssistantsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserAssistantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assistants    []*Assistant           `protobuf:"bytes,1,rep,name=Assistants,proto3" json:"Assistants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAssistantsResponse) Reset() {
	*x = GetUserAssistantsResponse{}
	mi := &file_clients_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAssistantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAssistantsResponse) ProtoMessage() {}

func (x *GetUserAssistantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAssistantsResponse.ProtoReflect.Descriptor instead.
func (*GetUserAssistantsResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserAssistantsResponse) GetAssistants() []*Assistant {
	if x != nil {
		return x.Assistants
	}
	return nil
}

type GetAssistantDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int64                  `protobuf:"varint,1,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssistantDocumentsRequest) Reset() {
	*x = GetAssistantDocumentsRequest{}
	mi := &file_clients_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssistantDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssistantDocumentsRequest) ProtoMessage() {}

func (x *GetAssistantDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssistantDocumentsRequest.ProtoReflect.Descriptor instead.
func (*GetAssistantDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{14}
}

func (x *GetAssistantDocumentsRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

type GetAssistantDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=Documents,proto3" json:"Documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssistantDocumentsResponse) Reset() {
	*x = GetAssistantDocumentsResponse{}
	mi := &file_clients_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssistantDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssistantDocumentsResponse) ProtoMessage() {}

func (x *GetAssistantDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssistantDocumentsResponse.ProtoReflect.Descriptor instead.
func (*GetAssistantDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{15}
}

func (x *GetAssistantDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

var File_clients_proto protoreflect.FileDescriptor

const file_clients_proto_rawDesc = "" +
	"\n" +
	"\rclients.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x02\n" +
	"\tAssistant\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x10\n" +
	"\x03Tag\x18\x04 \x01(\tR\x03Tag\x12\"\n" +
	"\fFirstMessage\x18\x05 \x01(\tR\fFirstMessage\x128\n" +
	"\tCreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12,\n" +
	"\x11TelegramBotExists\x18\a \x01(\bR\x11TelegramBotExists\x12&\n" +
	"\x0eTodayQuestions\x18\b \x01(\x03R\x0eTodayQuestions\x12.\n" +
	"\x12ThisMonthQuestions\x18\t \x01(\x03R\x12ThisMonthQuestions\"X\n" +
	"\bDocument\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12 \n" +
	"\vAssistantId\x18\x02 \x01(\x03R\vAssistantId\x12\x1a\n" +
	"\bFileName\x18\x03 \x01(\tR\bFileName\"z\n" +
	"\x16CreateAssistantRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x10\n" +
	"\x03Tag\x18\x03 \x01(\tR\x03Tag\x12\"\n" +
	"\fFirstMessage\x18\x04 \x01(\tR\fFirstMessage\";\n" +
	"\x17CreateAssistantResponse\x12 \n" +
	"\vAssistantId\x18\x01 \x01(\x03R\vAssistantId\"R\n" +
	"\x12AddDocumentRequest\x12 \n" +
	"\vAssistantId\x18\x01 \x01(\x03R\vAssistantId\x12\x1a\n" +
	"\bFileName\x18\x02 \x01(\tR\bFileName\"5\n" +
	"\x13AddDocumentResponse\x12\x1e\n" +
	"\n" +
	"DocumentId\x18\x01 \x01(\x03R\n" +
	"DocumentId\"R\n" +
	"\x16DeleteAssistantRequest\x12 \n" +
	"\vAssistantId\x18\x01 \x01(\x03R\vAssistantId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\"1\n" +
	"\x17DeleteAssistantResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\"O\n" +
	"\x15DeleteDocumentRequest\x12\x1e\n" +
	"\n" +
	"DocumentId\x18\x01 \x01(\x03R\n" +
	"DocumentId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\"0\n" +
	"\x16DeleteDocumentResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\"^\n" +
	"\x16GetOneAssistantRequest\x12 \n" +
	"\vAssistantId\x18\x01 \x01(\x03R\vAssistantId\x12\"\n" +
	"\fAssistantTag\x18\x02 \x01(\x03R\fAssistantTag\"C\n" +
	"\x17GetOneAssistantResponse\x12(\n" +
	"\tAssistant\x18\x01 \x01(\v2\n" +
	".AssistantR\tAssistant\"2\n" +
	"\x18GetUserAssistantsRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\"G\n" +
	"\x19GetUserAssistantsResponse\x12*\n" +
	"\n" +
	"Assistants\x18\x01 \x03(\v2\n" +
	".AssistantR\n" +
	"Assistants\"@\n" +
	"\x1cGetAssistantDocumentsRequest\x12 \n" +
	"\vAssistantId\x18\x01 \x01(\x03R\vAssistantId\"H\n" +
	"\x1dGetAssistantDocumentsResponse\x12'\n" +
	"\tDocuments\x18\x01 \x03(\v2\t.DocumentR\tDocuments2\xfc\x03\n" +
	"\aClients\x12D\n" +
	"\x0fCreateAssistant\x12\x17.CreateAssistantRequest\x1a\x18.CreateAssistantResponse\x128\n" +
	"\vAddDocument\x12\x13.AddDocumentRequest\x1a\x14.AddDocumentResponse\x12D\n" +
	"\x0fDeleteAssistant\x12\x17.DeleteAssistantRequest\x1a\x18.DeleteAssistantResponse\x12A\n" +
	"\x0eDeleteDocument\x12\x16.DeleteDocumentRequest\x1a\x17.DeleteDocumentResponse\x12D\n" +
	"\x0fGetOneAssistant\x12\x17.GetOneAssistantRequest\x1a\x18.GetOneAssistantResponse\x12J\n" +
	"\x11GetUserAssistants\x12\x19.GetUserAssistantsRequest\x1a\x1a.GetUserAssistantsResponse\x12V\n" +
	"\x15GetAssistantDocuments\x12\x1d.GetAssistantDocumentsRequest\x1a\x1e.GetAssistantDocumentsResponseB\tZ\a.;protob\x06proto3"

var (
	file_clients_proto_rawDescOnce sync.Once
	file_clients_proto_rawDescData []byte
)

func file_clients_proto_rawDescGZIP() []byte {
	file_clients_proto_rawDescOnce.Do(func() {
		file_clients_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clients_proto_rawDesc), len(file_clients_proto_rawDesc)))
	})
	return file_clients_proto_rawDescData
}

var file_clients_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_clients_proto_goTypes = []any{
	(*Assistant)(nil),                     // 0: Assistant
	(*Document)(nil),                      // 1: Document
	(*CreateAssistantRequest)(nil),        // 2: CreateAssistantRequest
	(*CreateAssistantResponse)(nil),       // 3: CreateAssistantResponse
	(*AddDocumentRequest)(nil),            // 4: AddDocumentRequest
	(*AddDocumentResponse)(nil),           // 5: AddDocumentResponse
	(*DeleteAssistantRequest)(nil),        // 6: DeleteAssistantRequest
	(*DeleteAssistantResponse)(nil),       // 7: DeleteAssistantResponse
	(*DeleteDocumentRequest)(nil),         // 8: DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil),        // 9: DeleteDocumentResponse
	(*GetOneAssistantRequest)(nil),        // 10: GetOneAssistantRequest
	(*GetOneAssistantResponse)(nil),       // 11: GetOneAssistantResponse
	(*GetUserAssistantsRequest)(nil),      // 12: GetUserAssistantsRequest
	(*GetUserAssistantsResponse)(nil),     // 13: GetUserAssistantsResponse
	(*GetAssistantDocumentsRequest)(nil),  // 14: GetAssistantDocumentsRequest
	(*GetAssistantDocumentsResponse)(nil), // 15: GetAssistantDocumentsResponse
	(*timestamppb.Timestamp)(nil),         // 16: google.protobuf.Timestamp
}
var file_clients_proto_depIdxs = []int32{
	16, // 0: Assistant.CreatedAt:type_name -> google.protobuf.Timestamp
	0,  // 1: GetOneAssistantResponse.Assistant:type_name -> Assistant
	0,  // 2: GetUserAssistantsResponse.Assistants:type_name -> Assistant
	1,  // 3: GetAssistantDocumentsResponse.Documents:type_name -> Document
	2,  // 4: Clients.CreateAssistant:input_type -> CreateAssistantRequest
	4,  // 5: Clients.AddDocument:input_type -> AddDocumentRequest
	6,  // 6: Clients.DeleteAssistant:input_type -> DeleteAssistantRequest
	8,  // 7: Clients.DeleteDocument:input_type -> DeleteDocumentRequest
	10, // 8: Clients.GetOneAssistant:input_type -> GetOneAssistantRequest
	12, // 9: Clients.GetUserAssistants:input_type -> GetUserAssistantsRequest
	14, // 10: Clients.GetAssistantDocuments:input_type -> GetAssistantDocumentsRequest
	3,  // 11: Clients.CreateAssistant:output_type -> CreateAssistantResponse
	5,  // 12: Clients.AddDocument:output_type -> AddDocumentResponse
	7,  // 13: Clients.DeleteAssistant:output_type -> DeleteAssistantResponse
	9,  // 14: Clients.DeleteDocument:output_type -> DeleteDocumentResponse
	11, // 15: Clients.GetOneAssistant:output_type -> GetOneAssistantResponse
	13, // 16: Clients.GetUserAssistants:output_type -> GetUserAssistantsResponse
	15, // 17: Clients.GetAssistantDocuments:output_type -> GetAssistantDocumentsResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_clients_proto_init() }
func file_clients_proto_init() {
	if File_clients_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clients_proto_rawDesc), len(file_clients_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clients_proto_goTypes,
		DependencyIndexes: file_clients_proto_depIdxs,
		MessageInfos:      file_clients_proto_msgTypes,
	}.Build()
	File_clients_proto = out.File
	file_clients_proto_goTypes = nil
	file_clients_proto_depIdxs = nil
}
