// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: clients.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Clients_CreateAssistant_FullMethodName          = "/Clients/CreateAssistant"
	Clients_AddDocument_FullMethodName              = "/Clients/AddDocument"
	Clients_DeleteAssistant_FullMethodName          = "/Clients/DeleteAssistant"
	Clients_DeleteDocument_FullMethodName           = "/Clients/DeleteDocument"
	Clients_GetOneAssistant_FullMethodName          = "/Clients/GetOneAssistant"
	Clients_GetUserAssistants_FullMethodName        = "/Clients/GetUserAssistants"
	Clients_GetAssistantDocuments_FullMethodName    = "/Clients/GetAssistantDocuments"
	Clients_UpdateAssistant_FullMethodName          = "/Clients/UpdateAssistant"
	Clients_GiveAnswer_FullMethodName               = "/Clients/GiveAnswer"
	Clients_GetAssistantGivenAnswers_FullMethodName = "/Clients/GetAssistantGivenAnswers"
	Clients_DeleteGivenAnswer_FullMethodName        = "/Clients/DeleteGivenAnswer"
	Clients_CreateAppeal_FullMethodName             = "/Clients/CreateAppeal"
	Clients_GetAssistantAppeals_FullMethodName      = "/Clients/GetAssistantAppeals"
	Clients_GetUserAssistantsAppeals_FullMethodName = "/Clients/GetUserAssistantsAppeals"
	Clients_AddClientToQueue_FullMethodName         = "/Clients/AddClientToQueue"
	Clients_GetOperatorChats_FullMethodName         = "/Clients/GetOperatorChats"
	Clients_GetUserOperators_FullMethodName         = "/Clients/GetUserOperators"
	Clients_GetOneQueueClient_FullMethodName        = "/Clients/GetOneQueueClient"
	Clients_GetChatMessages_FullMethodName          = "/Clients/GetChatMessages"
	Clients_CreateMessage_FullMethodName            = "/Clients/CreateMessage"
	Clients_CheckIsOperator_FullMethodName          = "/Clients/CheckIsOperator"
	Clients_NewOperator_FullMethodName              = "/Clients/NewOperator"
)

// ClientsClient is the client API for Clients service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientsClient interface {
	CreateAssistant(ctx context.Context, in *CreateAssistantRequest, opts ...grpc.CallOption) (*CreateAssistantResponse, error)
	AddDocument(ctx context.Context, in *AddDocumentRequest, opts ...grpc.CallOption) (*AddDocumentResponse, error)
	DeleteAssistant(ctx context.Context, in *DeleteAssistantRequest, opts ...grpc.CallOption) (*DeleteAssistantResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	GetOneAssistant(ctx context.Context, in *GetOneAssistantRequest, opts ...grpc.CallOption) (*GetOneAssistantResponse, error)
	GetUserAssistants(ctx context.Context, in *GetUserAssistantsRequest, opts ...grpc.CallOption) (*GetUserAssistantsResponse, error)
	GetAssistantDocuments(ctx context.Context, in *GetAssistantDocumentsRequest, opts ...grpc.CallOption) (*GetAssistantDocumentsResponse, error)
	UpdateAssistant(ctx context.Context, in *UpdateAssistantRequest, opts ...grpc.CallOption) (*UpdateAssistantResponse, error)
	GiveAnswer(ctx context.Context, in *GiveAnswerRequest, opts ...grpc.CallOption) (*GiveAnswerResponse, error)
	GetAssistantGivenAnswers(ctx context.Context, in *GetAssistantGivenAnswersRequest, opts ...grpc.CallOption) (*GetAssistantGivenAnswersResponse, error)
	DeleteGivenAnswer(ctx context.Context, in *DeleteGivenAnswerRequest, opts ...grpc.CallOption) (*DeleteGivenAnswerResponse, error)
	CreateAppeal(ctx context.Context, in *CreateAppealRequest, opts ...grpc.CallOption) (*CreateAppealResponse, error)
	GetAssistantAppeals(ctx context.Context, in *GetAssistantAppealsRequest, opts ...grpc.CallOption) (*GetAssistantAppealsResponse, error)
	GetUserAssistantsAppeals(ctx context.Context, in *GetUserAssistantsAppealsRequest, opts ...grpc.CallOption) (*GetUserAssistantsAppealsResponse, error)
	AddClientToQueue(ctx context.Context, in *AddClientToQueueRequest, opts ...grpc.CallOption) (*AddClientToQueueResponse, error)
	GetOperatorChats(ctx context.Context, in *GetOperatorChatsRequest, opts ...grpc.CallOption) (*GetOperatorChatsResponse, error)
	GetUserOperators(ctx context.Context, in *GetUserOperatorsRequest, opts ...grpc.CallOption) (*GetUserOperatorsResponse, error)
	GetOneQueueClient(ctx context.Context, in *GetOneQueueClientRequest, opts ...grpc.CallOption) (*GetOneQueueClientResponse, error)
	GetChatMessages(ctx context.Context, in *GetChatMessagesRequest, opts ...grpc.CallOption) (*GetChatMessagesResponse, error)
	CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error)
	CheckIsOperator(ctx context.Context, in *CheckIsOperatorRequest, opts ...grpc.CallOption) (*CheckIsOperatorResponse, error)
	NewOperator(ctx context.Context, in *NewOperatorRequest, opts ...grpc.CallOption) (*NewOperatorResponse, error)
}

type clientsClient struct {
	cc grpc.ClientConnInterface
}

func NewClientsClient(cc grpc.ClientConnInterface) ClientsClient {
	return &clientsClient{cc}
}

func (c *clientsClient) CreateAssistant(ctx context.Context, in *CreateAssistantRequest, opts ...grpc.CallOption) (*CreateAssistantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAssistantResponse)
	err := c.cc.Invoke(ctx, Clients_CreateAssistant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) AddDocument(ctx context.Context, in *AddDocumentRequest, opts ...grpc.CallOption) (*AddDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDocumentResponse)
	err := c.cc.Invoke(ctx, Clients_AddDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) DeleteAssistant(ctx context.Context, in *DeleteAssistantRequest, opts ...grpc.CallOption) (*DeleteAssistantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAssistantResponse)
	err := c.cc.Invoke(ctx, Clients_DeleteAssistant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDocumentResponse)
	err := c.cc.Invoke(ctx, Clients_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) GetOneAssistant(ctx context.Context, in *GetOneAssistantRequest, opts ...grpc.CallOption) (*GetOneAssistantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOneAssistantResponse)
	err := c.cc.Invoke(ctx, Clients_GetOneAssistant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) GetUserAssistants(ctx context.Context, in *GetUserAssistantsRequest, opts ...grpc.CallOption) (*GetUserAssistantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAssistantsResponse)
	err := c.cc.Invoke(ctx, Clients_GetUserAssistants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) GetAssistantDocuments(ctx context.Context, in *GetAssistantDocumentsRequest, opts ...grpc.CallOption) (*GetAssistantDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssistantDocumentsResponse)
	err := c.cc.Invoke(ctx, Clients_GetAssistantDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) UpdateAssistant(ctx context.Context, in *UpdateAssistantRequest, opts ...grpc.CallOption) (*UpdateAssistantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAssistantResponse)
	err := c.cc.Invoke(ctx, Clients_UpdateAssistant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) GiveAnswer(ctx context.Context, in *GiveAnswerRequest, opts ...grpc.CallOption) (*GiveAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GiveAnswerResponse)
	err := c.cc.Invoke(ctx, Clients_GiveAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) GetAssistantGivenAnswers(ctx context.Context, in *GetAssistantGivenAnswersRequest, opts ...grpc.CallOption) (*GetAssistantGivenAnswersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssistantGivenAnswersResponse)
	err := c.cc.Invoke(ctx, Clients_GetAssistantGivenAnswers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) DeleteGivenAnswer(ctx context.Context, in *DeleteGivenAnswerRequest, opts ...grpc.CallOption) (*DeleteGivenAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGivenAnswerResponse)
	err := c.cc.Invoke(ctx, Clients_DeleteGivenAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) CreateAppeal(ctx context.Context, in *CreateAppealRequest, opts ...grpc.CallOption) (*CreateAppealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAppealResponse)
	err := c.cc.Invoke(ctx, Clients_CreateAppeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) GetAssistantAppeals(ctx context.Context, in *GetAssistantAppealsRequest, opts ...grpc.CallOption) (*GetAssistantAppealsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssistantAppealsResponse)
	err := c.cc.Invoke(ctx, Clients_GetAssistantAppeals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) GetUserAssistantsAppeals(ctx context.Context, in *GetUserAssistantsAppealsRequest, opts ...grpc.CallOption) (*GetUserAssistantsAppealsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAssistantsAppealsResponse)
	err := c.cc.Invoke(ctx, Clients_GetUserAssistantsAppeals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) AddClientToQueue(ctx context.Context, in *AddClientToQueueRequest, opts ...grpc.CallOption) (*AddClientToQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddClientToQueueResponse)
	err := c.cc.Invoke(ctx, Clients_AddClientToQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) GetOperatorChats(ctx context.Context, in *GetOperatorChatsRequest, opts ...grpc.CallOption) (*GetOperatorChatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOperatorChatsResponse)
	err := c.cc.Invoke(ctx, Clients_GetOperatorChats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) GetUserOperators(ctx context.Context, in *GetUserOperatorsRequest, opts ...grpc.CallOption) (*GetUserOperatorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserOperatorsResponse)
	err := c.cc.Invoke(ctx, Clients_GetUserOperators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) GetOneQueueClient(ctx context.Context, in *GetOneQueueClientRequest, opts ...grpc.CallOption) (*GetOneQueueClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOneQueueClientResponse)
	err := c.cc.Invoke(ctx, Clients_GetOneQueueClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) GetChatMessages(ctx context.Context, in *GetChatMessagesRequest, opts ...grpc.CallOption) (*GetChatMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatMessagesResponse)
	err := c.cc.Invoke(ctx, Clients_GetChatMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMessageResponse)
	err := c.cc.Invoke(ctx, Clients_CreateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) CheckIsOperator(ctx context.Context, in *CheckIsOperatorRequest, opts ...grpc.CallOption) (*CheckIsOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckIsOperatorResponse)
	err := c.cc.Invoke(ctx, Clients_CheckIsOperator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) NewOperator(ctx context.Context, in *NewOperatorRequest, opts ...grpc.CallOption) (*NewOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewOperatorResponse)
	err := c.cc.Invoke(ctx, Clients_NewOperator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientsServer is the server API for Clients service.
// All implementations must embed UnimplementedClientsServer
// for forward compatibility.
type ClientsServer interface {
	CreateAssistant(context.Context, *CreateAssistantRequest) (*CreateAssistantResponse, error)
	AddDocument(context.Context, *AddDocumentRequest) (*AddDocumentResponse, error)
	DeleteAssistant(context.Context, *DeleteAssistantRequest) (*DeleteAssistantResponse, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	GetOneAssistant(context.Context, *GetOneAssistantRequest) (*GetOneAssistantResponse, error)
	GetUserAssistants(context.Context, *GetUserAssistantsRequest) (*GetUserAssistantsResponse, error)
	GetAssistantDocuments(context.Context, *GetAssistantDocumentsRequest) (*GetAssistantDocumentsResponse, error)
	UpdateAssistant(context.Context, *UpdateAssistantRequest) (*UpdateAssistantResponse, error)
	GiveAnswer(context.Context, *GiveAnswerRequest) (*GiveAnswerResponse, error)
	GetAssistantGivenAnswers(context.Context, *GetAssistantGivenAnswersRequest) (*GetAssistantGivenAnswersResponse, error)
	DeleteGivenAnswer(context.Context, *DeleteGivenAnswerRequest) (*DeleteGivenAnswerResponse, error)
	CreateAppeal(context.Context, *CreateAppealRequest) (*CreateAppealResponse, error)
	GetAssistantAppeals(context.Context, *GetAssistantAppealsRequest) (*GetAssistantAppealsResponse, error)
	GetUserAssistantsAppeals(context.Context, *GetUserAssistantsAppealsRequest) (*GetUserAssistantsAppealsResponse, error)
	AddClientToQueue(context.Context, *AddClientToQueueRequest) (*AddClientToQueueResponse, error)
	GetOperatorChats(context.Context, *GetOperatorChatsRequest) (*GetOperatorChatsResponse, error)
	GetUserOperators(context.Context, *GetUserOperatorsRequest) (*GetUserOperatorsResponse, error)
	GetOneQueueClient(context.Context, *GetOneQueueClientRequest) (*GetOneQueueClientResponse, error)
	GetChatMessages(context.Context, *GetChatMessagesRequest) (*GetChatMessagesResponse, error)
	CreateMessage(context.Context, *CreateMessageRequest) (*CreateMessageResponse, error)
	CheckIsOperator(context.Context, *CheckIsOperatorRequest) (*CheckIsOperatorResponse, error)
	NewOperator(context.Context, *NewOperatorRequest) (*NewOperatorResponse, error)
	mustEmbedUnimplementedClientsServer()
}

// UnimplementedClientsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientsServer struct{}

func (UnimplementedClientsServer) CreateAssistant(context.Context, *CreateAssistantRequest) (*CreateAssistantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAssistant not implemented")
}
func (UnimplementedClientsServer) AddDocument(context.Context, *AddDocumentRequest) (*AddDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDocument not implemented")
}
func (UnimplementedClientsServer) DeleteAssistant(context.Context, *DeleteAssistantRequest) (*DeleteAssistantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAssistant not implemented")
}
func (UnimplementedClientsServer) DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedClientsServer) GetOneAssistant(context.Context, *GetOneAssistantRequest) (*GetOneAssistantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOneAssistant not implemented")
}
func (UnimplementedClientsServer) GetUserAssistants(context.Context, *GetUserAssistantsRequest) (*GetUserAssistantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAssistants not implemented")
}
func (UnimplementedClientsServer) GetAssistantDocuments(context.Context, *GetAssistantDocumentsRequest) (*GetAssistantDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssistantDocuments not implemented")
}
func (UnimplementedClientsServer) UpdateAssistant(context.Context, *UpdateAssistantRequest) (*UpdateAssistantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAssistant not implemented")
}
func (UnimplementedClientsServer) GiveAnswer(context.Context, *GiveAnswerRequest) (*GiveAnswerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GiveAnswer not implemented")
}
func (UnimplementedClientsServer) GetAssistantGivenAnswers(context.Context, *GetAssistantGivenAnswersRequest) (*GetAssistantGivenAnswersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssistantGivenAnswers not implemented")
}
func (UnimplementedClientsServer) DeleteGivenAnswer(context.Context, *DeleteGivenAnswerRequest) (*DeleteGivenAnswerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGivenAnswer not implemented")
}
func (UnimplementedClientsServer) CreateAppeal(context.Context, *CreateAppealRequest) (*CreateAppealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAppeal not implemented")
}
func (UnimplementedClientsServer) GetAssistantAppeals(context.Context, *GetAssistantAppealsRequest) (*GetAssistantAppealsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssistantAppeals not implemented")
}
func (UnimplementedClientsServer) GetUserAssistantsAppeals(context.Context, *GetUserAssistantsAppealsRequest) (*GetUserAssistantsAppealsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAssistantsAppeals not implemented")
}
func (UnimplementedClientsServer) AddClientToQueue(context.Context, *AddClientToQueueRequest) (*AddClientToQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddClientToQueue not implemented")
}
func (UnimplementedClientsServer) GetOperatorChats(context.Context, *GetOperatorChatsRequest) (*GetOperatorChatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOperatorChats not implemented")
}
func (UnimplementedClientsServer) GetUserOperators(context.Context, *GetUserOperatorsRequest) (*GetUserOperatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOperators not implemented")
}
func (UnimplementedClientsServer) GetOneQueueClient(context.Context, *GetOneQueueClientRequest) (*GetOneQueueClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOneQueueClient not implemented")
}
func (UnimplementedClientsServer) GetChatMessages(context.Context, *GetChatMessagesRequest) (*GetChatMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatMessages not implemented")
}
func (UnimplementedClientsServer) CreateMessage(context.Context, *CreateMessageRequest) (*CreateMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMessage not implemented")
}
func (UnimplementedClientsServer) CheckIsOperator(context.Context, *CheckIsOperatorRequest) (*CheckIsOperatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIsOperator not implemented")
}
func (UnimplementedClientsServer) NewOperator(context.Context, *NewOperatorRequest) (*NewOperatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewOperator not implemented")
}
func (UnimplementedClientsServer) mustEmbedUnimplementedClientsServer() {}
func (UnimplementedClientsServer) testEmbeddedByValue()                 {}

// UnsafeClientsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientsServer will
// result in compilation errors.
type UnsafeClientsServer interface {
	mustEmbedUnimplementedClientsServer()
}

func RegisterClientsServer(s grpc.ServiceRegistrar, srv ClientsServer) {
	// If the following call pancis, it indicates UnimplementedClientsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Clients_ServiceDesc, srv)
}

func _Clients_CreateAssistant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssistantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).CreateAssistant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_CreateAssistant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).CreateAssistant(ctx, req.(*CreateAssistantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_AddDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).AddDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_AddDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).AddDocument(ctx, req.(*AddDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_DeleteAssistant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAssistantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).DeleteAssistant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_DeleteAssistant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).DeleteAssistant(ctx, req.(*DeleteAssistantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_GetOneAssistant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneAssistantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).GetOneAssistant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_GetOneAssistant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).GetOneAssistant(ctx, req.(*GetOneAssistantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_GetUserAssistants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAssistantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).GetUserAssistants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_GetUserAssistants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).GetUserAssistants(ctx, req.(*GetUserAssistantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_GetAssistantDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssistantDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).GetAssistantDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_GetAssistantDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).GetAssistantDocuments(ctx, req.(*GetAssistantDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_UpdateAssistant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssistantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).UpdateAssistant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_UpdateAssistant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).UpdateAssistant(ctx, req.(*UpdateAssistantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_GiveAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GiveAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).GiveAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_GiveAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).GiveAnswer(ctx, req.(*GiveAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_GetAssistantGivenAnswers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssistantGivenAnswersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).GetAssistantGivenAnswers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_GetAssistantGivenAnswers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).GetAssistantGivenAnswers(ctx, req.(*GetAssistantGivenAnswersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_DeleteGivenAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGivenAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).DeleteGivenAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_DeleteGivenAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).DeleteGivenAnswer(ctx, req.(*DeleteGivenAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_CreateAppeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).CreateAppeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_CreateAppeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).CreateAppeal(ctx, req.(*CreateAppealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_GetAssistantAppeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssistantAppealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).GetAssistantAppeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_GetAssistantAppeals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).GetAssistantAppeals(ctx, req.(*GetAssistantAppealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_GetUserAssistantsAppeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAssistantsAppealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).GetUserAssistantsAppeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_GetUserAssistantsAppeals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).GetUserAssistantsAppeals(ctx, req.(*GetUserAssistantsAppealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_AddClientToQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddClientToQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).AddClientToQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_AddClientToQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).AddClientToQueue(ctx, req.(*AddClientToQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_GetOperatorChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperatorChatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).GetOperatorChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_GetOperatorChats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).GetOperatorChats(ctx, req.(*GetOperatorChatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_GetUserOperators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserOperatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).GetUserOperators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_GetUserOperators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).GetUserOperators(ctx, req.(*GetUserOperatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_GetOneQueueClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneQueueClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).GetOneQueueClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_GetOneQueueClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).GetOneQueueClient(ctx, req.(*GetOneQueueClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_GetChatMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).GetChatMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_GetChatMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).GetChatMessages(ctx, req.(*GetChatMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_CreateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).CreateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_CheckIsOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckIsOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).CheckIsOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_CheckIsOperator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).CheckIsOperator(ctx, req.(*CheckIsOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_NewOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).NewOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Clients_NewOperator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).NewOperator(ctx, req.(*NewOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Clients_ServiceDesc is the grpc.ServiceDesc for Clients service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Clients_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Clients",
	HandlerType: (*ClientsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAssistant",
			Handler:    _Clients_CreateAssistant_Handler,
		},
		{
			MethodName: "AddDocument",
			Handler:    _Clients_AddDocument_Handler,
		},
		{
			MethodName: "DeleteAssistant",
			Handler:    _Clients_DeleteAssistant_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _Clients_DeleteDocument_Handler,
		},
		{
			MethodName: "GetOneAssistant",
			Handler:    _Clients_GetOneAssistant_Handler,
		},
		{
			MethodName: "GetUserAssistants",
			Handler:    _Clients_GetUserAssistants_Handler,
		},
		{
			MethodName: "GetAssistantDocuments",
			Handler:    _Clients_GetAssistantDocuments_Handler,
		},
		{
			MethodName: "UpdateAssistant",
			Handler:    _Clients_UpdateAssistant_Handler,
		},
		{
			MethodName: "GiveAnswer",
			Handler:    _Clients_GiveAnswer_Handler,
		},
		{
			MethodName: "GetAssistantGivenAnswers",
			Handler:    _Clients_GetAssistantGivenAnswers_Handler,
		},
		{
			MethodName: "DeleteGivenAnswer",
			Handler:    _Clients_DeleteGivenAnswer_Handler,
		},
		{
			MethodName: "CreateAppeal",
			Handler:    _Clients_CreateAppeal_Handler,
		},
		{
			MethodName: "GetAssistantAppeals",
			Handler:    _Clients_GetAssistantAppeals_Handler,
		},
		{
			MethodName: "GetUserAssistantsAppeals",
			Handler:    _Clients_GetUserAssistantsAppeals_Handler,
		},
		{
			MethodName: "AddClientToQueue",
			Handler:    _Clients_AddClientToQueue_Handler,
		},
		{
			MethodName: "GetOperatorChats",
			Handler:    _Clients_GetOperatorChats_Handler,
		},
		{
			MethodName: "GetUserOperators",
			Handler:    _Clients_GetUserOperators_Handler,
		},
		{
			MethodName: "GetOneQueueClient",
			Handler:    _Clients_GetOneQueueClient_Handler,
		},
		{
			MethodName: "GetChatMessages",
			Handler:    _Clients_GetChatMessages_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _Clients_CreateMessage_Handler,
		},
		{
			MethodName: "CheckIsOperator",
			Handler:    _Clients_CheckIsOperator_Handler,
		},
		{
			MethodName: "NewOperator",
			Handler:    _Clients_NewOperator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clients.proto",
}
