// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.1
// source: clients.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Assistant struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId             int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Tag                string                 `protobuf:"bytes,4,opt,name=Tag,proto3" json:"Tag,omitempty"`
	FirstMessage       string                 `protobuf:"bytes,5,opt,name=FirstMessage,proto3" json:"FirstMessage,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	TelegramBotExists  bool                   `protobuf:"varint,7,opt,name=TelegramBotExists,proto3" json:"TelegramBotExists,omitempty"`
	TodayQuestions     int64                  `protobuf:"varint,8,opt,name=TodayQuestions,proto3" json:"TodayQuestions,omitempty"`
	ThisMonthQuestions int64                  `protobuf:"varint,9,opt,name=ThisMonthQuestions,proto3" json:"ThisMonthQuestions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Assistant) Reset() {
	*x = Assistant{}
	mi := &file_clients_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assistant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assistant) ProtoMessage() {}

func (x *Assistant) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assistant.ProtoReflect.Descriptor instead.
func (*Assistant) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{0}
}

func (x *Assistant) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Assistant) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Assistant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Assistant) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Assistant) GetFirstMessage() string {
	if x != nil {
		return x.FirstMessage
	}
	return ""
}

func (x *Assistant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Assistant) GetTelegramBotExists() bool {
	if x != nil {
		return x.TelegramBotExists
	}
	return false
}

func (x *Assistant) GetTodayQuestions() int64 {
	if x != nil {
		return x.TodayQuestions
	}
	return 0
}

func (x *Assistant) GetThisMonthQuestions() int64 {
	if x != nil {
		return x.ThisMonthQuestions
	}
	return 0
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	AssistantId   int64                  `protobuf:"varint,2,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=FileName,proto3" json:"FileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_clients_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Document) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *Document) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GivenAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	AssistantId   int64                  `protobuf:"varint,2,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Question      string                 `protobuf:"bytes,4,opt,name=Question,proto3" json:"Question,omitempty"`
	Answer        string                 `protobuf:"bytes,5,opt,name=Answer,proto3" json:"Answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GivenAnswer) Reset() {
	*x = GivenAnswer{}
	mi := &file_clients_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GivenAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GivenAnswer) ProtoMessage() {}

func (x *GivenAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GivenAnswer.ProtoReflect.Descriptor instead.
func (*GivenAnswer) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{2}
}

func (x *GivenAnswer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GivenAnswer) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *GivenAnswer) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GivenAnswer) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *GivenAnswer) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type Appeal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserQuestion    string                 `protobuf:"bytes,2,opt,name=UserQuestion,proto3" json:"UserQuestion,omitempty"`
	AssistantAnswer string                 `protobuf:"bytes,3,opt,name=AssistantAnswer,proto3" json:"AssistantAnswer,omitempty"`
	UserComment     string                 `protobuf:"bytes,4,opt,name=UserComment,proto3" json:"UserComment,omitempty"`
	AssistantId     int64                  `protobuf:"varint,5,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	ChanksId        []int64                `protobuf:"varint,6,rep,packed,name=ChanksId,proto3" json:"ChanksId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Appeal) Reset() {
	*x = Appeal{}
	mi := &file_clients_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appeal) ProtoMessage() {}

func (x *Appeal) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appeal.ProtoReflect.Descriptor instead.
func (*Appeal) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{3}
}

func (x *Appeal) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Appeal) GetUserQuestion() string {
	if x != nil {
		return x.UserQuestion
	}
	return ""
}

func (x *Appeal) GetAssistantAnswer() string {
	if x != nil {
		return x.AssistantAnswer
	}
	return ""
}

func (x *Appeal) GetUserComment() string {
	if x != nil {
		return x.UserComment
	}
	return ""
}

func (x *Appeal) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *Appeal) GetChanksId() []int64 {
	if x != nil {
		return x.ChanksId
	}
	return nil
}

type CreateAssistantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=Tag,proto3" json:"Tag,omitempty"`
	FirstMessage  string                 `protobuf:"bytes,4,opt,name=FirstMessage,proto3" json:"FirstMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssistantRequest) Reset() {
	*x = CreateAssistantRequest{}
	mi := &file_clients_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssistantRequest) ProtoMessage() {}

func (x *CreateAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssistantRequest.ProtoReflect.Descriptor instead.
func (*CreateAssistantRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAssistantRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateAssistantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAssistantRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *CreateAssistantRequest) GetFirstMessage() string {
	if x != nil {
		return x.FirstMessage
	}
	return ""
}

type CreateAssistantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int64                  `protobuf:"varint,1,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	APIToken      string                 `protobuf:"bytes,2,opt,name=APIToken,proto3" json:"APIToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssistantResponse) Reset() {
	*x = CreateAssistantResponse{}
	mi := &file_clients_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssistantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssistantResponse) ProtoMessage() {}

func (x *CreateAssistantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssistantResponse.ProtoReflect.Descriptor instead.
func (*CreateAssistantResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAssistantResponse) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *CreateAssistantResponse) GetAPIToken() string {
	if x != nil {
		return x.APIToken
	}
	return ""
}

type AddDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int64                  `protobuf:"varint,1,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=FileName,proto3" json:"FileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDocumentRequest) Reset() {
	*x = AddDocumentRequest{}
	mi := &file_clients_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDocumentRequest) ProtoMessage() {}

func (x *AddDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDocumentRequest.ProtoReflect.Descriptor instead.
func (*AddDocumentRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{6}
}

func (x *AddDocumentRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *AddDocumentRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type AddDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    int64                  `protobuf:"varint,1,opt,name=DocumentId,proto3" json:"DocumentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDocumentResponse) Reset() {
	*x = AddDocumentResponse{}
	mi := &file_clients_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDocumentResponse) ProtoMessage() {}

func (x *AddDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDocumentResponse.ProtoReflect.Descriptor instead.
func (*AddDocumentResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{7}
}

func (x *AddDocumentResponse) GetDocumentId() int64 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

type DeleteAssistantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int64                  `protobuf:"varint,1,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssistantRequest) Reset() {
	*x = DeleteAssistantRequest{}
	mi := &file_clients_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssistantRequest) ProtoMessage() {}

func (x *DeleteAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssistantRequest.ProtoReflect.Descriptor instead.
func (*DeleteAssistantRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAssistantRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *DeleteAssistantRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteAssistantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssistantResponse) Reset() {
	*x = DeleteAssistantResponse{}
	mi := &file_clients_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssistantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssistantResponse) ProtoMessage() {}

func (x *DeleteAssistantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssistantResponse.ProtoReflect.Descriptor instead.
func (*DeleteAssistantResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAssistantResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    int64                  `protobuf:"varint,1,opt,name=DocumentId,proto3" json:"DocumentId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_clients_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDocumentRequest) GetDocumentId() int64 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

func (x *DeleteDocumentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_clients_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteDocumentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetOneAssistantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int64                  `protobuf:"varint,1,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	AssistantTag  string                 `protobuf:"bytes,2,opt,name=AssistantTag,proto3" json:"AssistantTag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneAssistantRequest) Reset() {
	*x = GetOneAssistantRequest{}
	mi := &file_clients_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneAssistantRequest) ProtoMessage() {}

func (x *GetOneAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneAssistantRequest.ProtoReflect.Descriptor instead.
func (*GetOneAssistantRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{12}
}

func (x *GetOneAssistantRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *GetOneAssistantRequest) GetAssistantTag() string {
	if x != nil {
		return x.AssistantTag
	}
	return ""
}

type GetOneAssistantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assistant     *Assistant             `protobuf:"bytes,1,opt,name=Assistant,proto3" json:"Assistant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneAssistantResponse) Reset() {
	*x = GetOneAssistantResponse{}
	mi := &file_clients_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneAssistantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneAssistantResponse) ProtoMessage() {}

func (x *GetOneAssistantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneAssistantResponse.ProtoReflect.Descriptor instead.
func (*GetOneAssistantResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{13}
}

func (x *GetOneAssistantResponse) GetAssistant() *Assistant {
	if x != nil {
		return x.Assistant
	}
	return nil
}

type GetUserAssistantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAssistantsRequest) Reset() {
	*x = GetUserAssistantsRequest{}
	mi := &file_clients_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAssistantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAssistantsRequest) ProtoMessage() {}

func (x *GetUserAssistantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAssistantsRequest.ProtoReflect.Descriptor instead.
func (*GetUserAssistantsRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserAssistantsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserAssistantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assistants    []*Assistant           `protobuf:"bytes,1,rep,name=Assistants,proto3" json:"Assistants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAssistantsResponse) Reset() {
	*x = GetUserAssistantsResponse{}
	mi := &file_clients_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAssistantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAssistantsResponse) ProtoMessage() {}

func (x *GetUserAssistantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAssistantsResponse.ProtoReflect.Descriptor instead.
func (*GetUserAssistantsResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserAssistantsResponse) GetAssistants() []*Assistant {
	if x != nil {
		return x.Assistants
	}
	return nil
}

type GetAssistantDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int64                  `protobuf:"varint,1,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssistantDocumentsRequest) Reset() {
	*x = GetAssistantDocumentsRequest{}
	mi := &file_clients_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssistantDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssistantDocumentsRequest) ProtoMessage() {}

func (x *GetAssistantDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssistantDocumentsRequest.ProtoReflect.Descriptor instead.
func (*GetAssistantDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{16}
}

func (x *GetAssistantDocumentsRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

type GetAssistantDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=Documents,proto3" json:"Documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssistantDocumentsResponse) Reset() {
	*x = GetAssistantDocumentsResponse{}
	mi := &file_clients_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssistantDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssistantDocumentsResponse) ProtoMessage() {}

func (x *GetAssistantDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssistantDocumentsResponse.ProtoReflect.Descriptor instead.
func (*GetAssistantDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{17}
}

func (x *GetAssistantDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

type UpdateAssistantRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	NewAssistantName         string                 `protobuf:"bytes,1,opt,name=NewAssistantName,proto3" json:"NewAssistantName,omitempty"`
	NewAssistantFirstMessage string                 `protobuf:"bytes,2,opt,name=NewAssistantFirstMessage,proto3" json:"NewAssistantFirstMessage,omitempty"`
	AssistantId              int64                  `protobuf:"varint,3,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	UserId                   int64                  `protobuf:"varint,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UpdateAssistantRequest) Reset() {
	*x = UpdateAssistantRequest{}
	mi := &file_clients_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssistantRequest) ProtoMessage() {}

func (x *UpdateAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssistantRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssistantRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateAssistantRequest) GetNewAssistantName() string {
	if x != nil {
		return x.NewAssistantName
	}
	return ""
}

func (x *UpdateAssistantRequest) GetNewAssistantFirstMessage() string {
	if x != nil {
		return x.NewAssistantFirstMessage
	}
	return ""
}

func (x *UpdateAssistantRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *UpdateAssistantRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateAssistantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssistantResponse) Reset() {
	*x = UpdateAssistantResponse{}
	mi := &file_clients_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssistantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssistantResponse) ProtoMessage() {}

func (x *UpdateAssistantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssistantResponse.ProtoReflect.Descriptor instead.
func (*UpdateAssistantResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateAssistantResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GiveAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int64                  `protobuf:"varint,1,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=Question,proto3" json:"Question,omitempty"`
	Answer        string                 `protobuf:"bytes,4,opt,name=Answer,proto3" json:"Answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiveAnswerRequest) Reset() {
	*x = GiveAnswerRequest{}
	mi := &file_clients_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiveAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveAnswerRequest) ProtoMessage() {}

func (x *GiveAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveAnswerRequest.ProtoReflect.Descriptor instead.
func (*GiveAnswerRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{20}
}

func (x *GiveAnswerRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *GiveAnswerRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GiveAnswerRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *GiveAnswerRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type GiveAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiveAnswerResponse) Reset() {
	*x = GiveAnswerResponse{}
	mi := &file_clients_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiveAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveAnswerResponse) ProtoMessage() {}

func (x *GiveAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveAnswerResponse.ProtoReflect.Descriptor instead.
func (*GiveAnswerResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{21}
}

func (x *GiveAnswerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetAssistantGivenAnswersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assistantid   int64                  `protobuf:"varint,1,opt,name=Assistantid,proto3" json:"Assistantid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssistantGivenAnswersRequest) Reset() {
	*x = GetAssistantGivenAnswersRequest{}
	mi := &file_clients_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssistantGivenAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssistantGivenAnswersRequest) ProtoMessage() {}

func (x *GetAssistantGivenAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssistantGivenAnswersRequest.ProtoReflect.Descriptor instead.
func (*GetAssistantGivenAnswersRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{22}
}

func (x *GetAssistantGivenAnswersRequest) GetAssistantid() int64 {
	if x != nil {
		return x.Assistantid
	}
	return 0
}

type GetAssistantGivenAnswersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GivenAnswers  []*GivenAnswer         `protobuf:"bytes,1,rep,name=GivenAnswers,proto3" json:"GivenAnswers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssistantGivenAnswersResponse) Reset() {
	*x = GetAssistantGivenAnswersResponse{}
	mi := &file_clients_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssistantGivenAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssistantGivenAnswersResponse) ProtoMessage() {}

func (x *GetAssistantGivenAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssistantGivenAnswersResponse.ProtoReflect.Descriptor instead.
func (*GetAssistantGivenAnswersResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{23}
}

func (x *GetAssistantGivenAnswersResponse) GetGivenAnswers() []*GivenAnswer {
	if x != nil {
		return x.GivenAnswers
	}
	return nil
}

type DeleteGivenAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnswerId      int64                  `protobuf:"varint,1,opt,name=AnswerId,proto3" json:"AnswerId,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGivenAnswerRequest) Reset() {
	*x = DeleteGivenAnswerRequest{}
	mi := &file_clients_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGivenAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGivenAnswerRequest) ProtoMessage() {}

func (x *DeleteGivenAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGivenAnswerRequest.ProtoReflect.Descriptor instead.
func (*DeleteGivenAnswerRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteGivenAnswerRequest) GetAnswerId() int64 {
	if x != nil {
		return x.AnswerId
	}
	return 0
}

func (x *DeleteGivenAnswerRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteGivenAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGivenAnswerResponse) Reset() {
	*x = DeleteGivenAnswerResponse{}
	mi := &file_clients_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGivenAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGivenAnswerResponse) ProtoMessage() {}

func (x *DeleteGivenAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGivenAnswerResponse.ProtoReflect.Descriptor instead.
func (*DeleteGivenAnswerResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteGivenAnswerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateAppealRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserQuestion    string                 `protobuf:"bytes,1,opt,name=UserQuestion,proto3" json:"UserQuestion,omitempty"`
	AssistantAnswer string                 `protobuf:"bytes,2,opt,name=AssistantAnswer,proto3" json:"AssistantAnswer,omitempty"`
	UserComment     string                 `protobuf:"bytes,3,opt,name=UserComment,proto3" json:"UserComment,omitempty"`
	AssistantId     int64                  `protobuf:"varint,4,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	ChanksId        []int64                `protobuf:"varint,5,rep,packed,name=ChanksId,proto3" json:"ChanksId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateAppealRequest) Reset() {
	*x = CreateAppealRequest{}
	mi := &file_clients_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppealRequest) ProtoMessage() {}

func (x *CreateAppealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppealRequest.ProtoReflect.Descriptor instead.
func (*CreateAppealRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{26}
}

func (x *CreateAppealRequest) GetUserQuestion() string {
	if x != nil {
		return x.UserQuestion
	}
	return ""
}

func (x *CreateAppealRequest) GetAssistantAnswer() string {
	if x != nil {
		return x.AssistantAnswer
	}
	return ""
}

func (x *CreateAppealRequest) GetUserComment() string {
	if x != nil {
		return x.UserComment
	}
	return ""
}

func (x *CreateAppealRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *CreateAppealRequest) GetChanksId() []int64 {
	if x != nil {
		return x.ChanksId
	}
	return nil
}

type CreateAppealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppealResponse) Reset() {
	*x = CreateAppealResponse{}
	mi := &file_clients_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppealResponse) ProtoMessage() {}

func (x *CreateAppealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppealResponse.ProtoReflect.Descriptor instead.
func (*CreateAppealResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{27}
}

func (x *CreateAppealResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetAssistantAppealsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssistantId   int64                  `protobuf:"varint,1,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssistantAppealsRequest) Reset() {
	*x = GetAssistantAppealsRequest{}
	mi := &file_clients_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssistantAppealsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssistantAppealsRequest) ProtoMessage() {}

func (x *GetAssistantAppealsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssistantAppealsRequest.ProtoReflect.Descriptor instead.
func (*GetAssistantAppealsRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{28}
}

func (x *GetAssistantAppealsRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

type GetAssistantAppealsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appeals       []*Appeal              `protobuf:"bytes,1,rep,name=Appeals,proto3" json:"Appeals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssistantAppealsResponse) Reset() {
	*x = GetAssistantAppealsResponse{}
	mi := &file_clients_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssistantAppealsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssistantAppealsResponse) ProtoMessage() {}

func (x *GetAssistantAppealsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssistantAppealsResponse.ProtoReflect.Descriptor instead.
func (*GetAssistantAppealsResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{29}
}

func (x *GetAssistantAppealsResponse) GetAppeals() []*Appeal {
	if x != nil {
		return x.Appeals
	}
	return nil
}

type GetUserAssistantsAppealsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAssistantsAppealsRequest) Reset() {
	*x = GetUserAssistantsAppealsRequest{}
	mi := &file_clients_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAssistantsAppealsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAssistantsAppealsRequest) ProtoMessage() {}

func (x *GetUserAssistantsAppealsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAssistantsAppealsRequest.ProtoReflect.Descriptor instead.
func (*GetUserAssistantsAppealsRequest) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{30}
}

func (x *GetUserAssistantsAppealsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserAssistantsAppealsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appeals       []*Appeal              `protobuf:"bytes,1,rep,name=Appeals,proto3" json:"Appeals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAssistantsAppealsResponse) Reset() {
	*x = GetUserAssistantsAppealsResponse{}
	mi := &file_clients_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAssistantsAppealsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAssistantsAppealsResponse) ProtoMessage() {}

func (x *GetUserAssistantsAppealsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clients_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAssistantsAppealsResponse.ProtoReflect.Descriptor instead.
func (*GetUserAssistantsAppealsResponse) Descriptor() ([]byte, []int) {
	return file_clients_proto_rawDescGZIP(), []int{31}
}

func (x *GetUserAssistantsAppealsResponse) GetAppeals() []*Appeal {
	if x != nil {
		return x.Appeals
	}
	return nil
}

var File_clients_proto protoreflect.FileDescriptor

const file_clients_proto_rawDesc = "" +
	"\n" +
	"\rclients.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x02\n" +
	"\tAssistant\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x10\n" +
	"\x03Tag\x18\x04 \x01(\tR\x03Tag\x12\"\n" +
	"\fFirstMessage\x18\x05 \x01(\tR\fFirstMessage\x128\n" +
	"\tCreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12,\n" +
	"\x11TelegramBotExists\x18\a \x01(\bR\x11TelegramBotExists\x12&\n" +
	"\x0eTodayQuestions\x18\b \x01(\x03R\x0eTodayQuestions\x12.\n" +
	"\x12ThisMonthQuestions\x18\t \x01(\x03R\x12ThisMonthQuestions\"X\n" +
	"\bDocument\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12 \n" +
	"\vAssistantId\x18\x02 \x01(\x03R\vAssistantId\x12\x1a\n" +
	"\bFileName\x18\x03 \x01(\tR\bFileName\"\x8b\x01\n" +
	"\vGivenAnswer\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12 \n" +
	"\vAssistantId\x18\x02 \x01(\x03R\vAssistantId\x12\x16\n" +
	"\x06UserId\x18\x03 \x01(\x03R\x06UserId\x12\x1a\n" +
	"\bQuestion\x18\x04 \x01(\tR\bQuestion\x12\x16\n" +
	"\x06Answer\x18\x05 \x01(\tR\x06Answer\"\xc6\x01\n" +
	"\x06Appeal\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\"\n" +
	"\fUserQuestion\x18\x02 \x01(\tR\fUserQuestion\x12(\n" +
	"\x0fAssistantAnswer\x18\x03 \x01(\tR\x0fAssistantAnswer\x12 \n" +
	"\vUserComment\x18\x04 \x01(\tR\vUserComment\x12 \n" +
	"\vAssistantId\x18\x05 \x01(\x03R\vAssistantId\x12\x1a\n" +
	"\bChanksId\x18\x06 \x03(\x03R\bChanksId\"z\n" +
	"\x16CreateAssistantRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x10\n" +
	"\x03Tag\x18\x03 \x01(\tR\x03Tag\x12\"\n" +
	"\fFirstMessage\x18\x04 \x01(\tR\fFirstMessage\"W\n" +
	"\x17CreateAssistantResponse\x12 \n" +
	"\vAssistantId\x18\x01 \x01(\x03R\vAssistantId\x12\x1a\n" +
	"\bAPIToken\x18\x02 \x01(\tR\bAPIToken\"R\n" +
	"\x12AddDocumentRequest\x12 \n" +
	"\vAssistantId\x18\x01 \x01(\x03R\vAssistantId\x12\x1a\n" +
	"\bFileName\x18\x02 \x01(\tR\bFileName\"5\n" +
	"\x13AddDocumentResponse\x12\x1e\n" +
	"\n" +
	"DocumentId\x18\x01 \x01(\x03R\n" +
	"DocumentId\"R\n" +
	"\x16DeleteAssistantRequest\x12 \n" +
	"\vAssistantId\x18\x01 \x01(\x03R\vAssistantId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\"1\n" +
	"\x17DeleteAssistantResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\"O\n" +
	"\x15DeleteDocumentRequest\x12\x1e\n" +
	"\n" +
	"DocumentId\x18\x01 \x01(\x03R\n" +
	"DocumentId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\"0\n" +
	"\x16DeleteDocumentResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\"^\n" +
	"\x16GetOneAssistantRequest\x12 \n" +
	"\vAssistantId\x18\x01 \x01(\x03R\vAssistantId\x12\"\n" +
	"\fAssistantTag\x18\x02 \x01(\tR\fAssistantTag\"C\n" +
	"\x17GetOneAssistantResponse\x12(\n" +
	"\tAssistant\x18\x01 \x01(\v2\n" +
	".AssistantR\tAssistant\"2\n" +
	"\x18GetUserAssistantsRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\"G\n" +
	"\x19GetUserAssistantsResponse\x12*\n" +
	"\n" +
	"Assistants\x18\x01 \x03(\v2\n" +
	".AssistantR\n" +
	"Assistants\"@\n" +
	"\x1cGetAssistantDocumentsRequest\x12 \n" +
	"\vAssistantId\x18\x01 \x01(\x03R\vAssistantId\"H\n" +
	"\x1dGetAssistantDocumentsResponse\x12'\n" +
	"\tDocuments\x18\x01 \x03(\v2\t.DocumentR\tDocuments\"\xba\x01\n" +
	"\x16UpdateAssistantRequest\x12*\n" +
	"\x10NewAssistantName\x18\x01 \x01(\tR\x10NewAssistantName\x12:\n" +
	"\x18NewAssistantFirstMessage\x18\x02 \x01(\tR\x18NewAssistantFirstMessage\x12 \n" +
	"\vAssistantId\x18\x03 \x01(\x03R\vAssistantId\x12\x16\n" +
	"\x06UserId\x18\x04 \x01(\x03R\x06UserId\"1\n" +
	"\x17UpdateAssistantResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\"\x81\x01\n" +
	"\x11GiveAnswerRequest\x12 \n" +
	"\vAssistantId\x18\x01 \x01(\x03R\vAssistantId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x1a\n" +
	"\bQuestion\x18\x03 \x01(\tR\bQuestion\x12\x16\n" +
	"\x06Answer\x18\x04 \x01(\tR\x06Answer\",\n" +
	"\x12GiveAnswerResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\"C\n" +
	"\x1fGetAssistantGivenAnswersRequest\x12 \n" +
	"\vAssistantid\x18\x01 \x01(\x03R\vAssistantid\"T\n" +
	" GetAssistantGivenAnswersResponse\x120\n" +
	"\fGivenAnswers\x18\x01 \x03(\v2\f.GivenAnswerR\fGivenAnswers\"N\n" +
	"\x18DeleteGivenAnswerRequest\x12\x1a\n" +
	"\bAnswerId\x18\x01 \x01(\x03R\bAnswerId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\"3\n" +
	"\x19DeleteGivenAnswerResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\"\xc3\x01\n" +
	"\x13CreateAppealRequest\x12\"\n" +
	"\fUserQuestion\x18\x01 \x01(\tR\fUserQuestion\x12(\n" +
	"\x0fAssistantAnswer\x18\x02 \x01(\tR\x0fAssistantAnswer\x12 \n" +
	"\vUserComment\x18\x03 \x01(\tR\vUserComment\x12 \n" +
	"\vAssistantId\x18\x04 \x01(\x03R\vAssistantId\x12\x1a\n" +
	"\bChanksId\x18\x05 \x03(\x03R\bChanksId\".\n" +
	"\x14CreateAppealResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\">\n" +
	"\x1aGetAssistantAppealsRequest\x12 \n" +
	"\vAssistantId\x18\x01 \x01(\x03R\vAssistantId\"@\n" +
	"\x1bGetAssistantAppealsResponse\x12!\n" +
	"\aAppeals\x18\x01 \x03(\v2\a.AppealR\aAppeals\"9\n" +
	"\x1fGetUserAssistantsAppealsRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\"E\n" +
	" GetUserAssistantsAppealsResponse\x12!\n" +
	"\aAppeals\x18\x01 \x03(\v2\a.AppealR\aAppeals2\x96\b\n" +
	"\aClients\x12D\n" +
	"\x0fCreateAssistant\x12\x17.CreateAssistantRequest\x1a\x18.CreateAssistantResponse\x128\n" +
	"\vAddDocument\x12\x13.AddDocumentRequest\x1a\x14.AddDocumentResponse\x12D\n" +
	"\x0fDeleteAssistant\x12\x17.DeleteAssistantRequest\x1a\x18.DeleteAssistantResponse\x12A\n" +
	"\x0eDeleteDocument\x12\x16.DeleteDocumentRequest\x1a\x17.DeleteDocumentResponse\x12D\n" +
	"\x0fGetOneAssistant\x12\x17.GetOneAssistantRequest\x1a\x18.GetOneAssistantResponse\x12J\n" +
	"\x11GetUserAssistants\x12\x19.GetUserAssistantsRequest\x1a\x1a.GetUserAssistantsResponse\x12V\n" +
	"\x15GetAssistantDocuments\x12\x1d.GetAssistantDocumentsRequest\x1a\x1e.GetAssistantDocumentsResponse\x12D\n" +
	"\x0fUpdateAssistant\x12\x17.UpdateAssistantRequest\x1a\x18.UpdateAssistantResponse\x125\n" +
	"\n" +
	"GiveAnswer\x12\x12.GiveAnswerRequest\x1a\x13.GiveAnswerResponse\x12_\n" +
	"\x18GetAssistantGivenAnswers\x12 .GetAssistantGivenAnswersRequest\x1a!.GetAssistantGivenAnswersResponse\x12J\n" +
	"\x11DeleteGivenAnswer\x12\x19.DeleteGivenAnswerRequest\x1a\x1a.DeleteGivenAnswerResponse\x12;\n" +
	"\fCreateAppeal\x12\x14.CreateAppealRequest\x1a\x15.CreateAppealResponse\x12P\n" +
	"\x13GetAssistantAppeals\x12\x1b.GetAssistantAppealsRequest\x1a\x1c.GetAssistantAppealsResponse\x12_\n" +
	"\x18GetUserAssistantsAppeals\x12 .GetUserAssistantsAppealsRequest\x1a!.GetUserAssistantsAppealsResponseB\tZ\a.;protob\x06proto3"

var (
	file_clients_proto_rawDescOnce sync.Once
	file_clients_proto_rawDescData []byte
)

func file_clients_proto_rawDescGZIP() []byte {
	file_clients_proto_rawDescOnce.Do(func() {
		file_clients_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clients_proto_rawDesc), len(file_clients_proto_rawDesc)))
	})
	return file_clients_proto_rawDescData
}

var file_clients_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_clients_proto_goTypes = []any{
	(*Assistant)(nil),                        // 0: Assistant
	(*Document)(nil),                         // 1: Document
	(*GivenAnswer)(nil),                      // 2: GivenAnswer
	(*Appeal)(nil),                           // 3: Appeal
	(*CreateAssistantRequest)(nil),           // 4: CreateAssistantRequest
	(*CreateAssistantResponse)(nil),          // 5: CreateAssistantResponse
	(*AddDocumentRequest)(nil),               // 6: AddDocumentRequest
	(*AddDocumentResponse)(nil),              // 7: AddDocumentResponse
	(*DeleteAssistantRequest)(nil),           // 8: DeleteAssistantRequest
	(*DeleteAssistantResponse)(nil),          // 9: DeleteAssistantResponse
	(*DeleteDocumentRequest)(nil),            // 10: DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil),           // 11: DeleteDocumentResponse
	(*GetOneAssistantRequest)(nil),           // 12: GetOneAssistantRequest
	(*GetOneAssistantResponse)(nil),          // 13: GetOneAssistantResponse
	(*GetUserAssistantsRequest)(nil),         // 14: GetUserAssistantsRequest
	(*GetUserAssistantsResponse)(nil),        // 15: GetUserAssistantsResponse
	(*GetAssistantDocumentsRequest)(nil),     // 16: GetAssistantDocumentsRequest
	(*GetAssistantDocumentsResponse)(nil),    // 17: GetAssistantDocumentsResponse
	(*UpdateAssistantRequest)(nil),           // 18: UpdateAssistantRequest
	(*UpdateAssistantResponse)(nil),          // 19: UpdateAssistantResponse
	(*GiveAnswerRequest)(nil),                // 20: GiveAnswerRequest
	(*GiveAnswerResponse)(nil),               // 21: GiveAnswerResponse
	(*GetAssistantGivenAnswersRequest)(nil),  // 22: GetAssistantGivenAnswersRequest
	(*GetAssistantGivenAnswersResponse)(nil), // 23: GetAssistantGivenAnswersResponse
	(*DeleteGivenAnswerRequest)(nil),         // 24: DeleteGivenAnswerRequest
	(*DeleteGivenAnswerResponse)(nil),        // 25: DeleteGivenAnswerResponse
	(*CreateAppealRequest)(nil),              // 26: CreateAppealRequest
	(*CreateAppealResponse)(nil),             // 27: CreateAppealResponse
	(*GetAssistantAppealsRequest)(nil),       // 28: GetAssistantAppealsRequest
	(*GetAssistantAppealsResponse)(nil),      // 29: GetAssistantAppealsResponse
	(*GetUserAssistantsAppealsRequest)(nil),  // 30: GetUserAssistantsAppealsRequest
	(*GetUserAssistantsAppealsResponse)(nil), // 31: GetUserAssistantsAppealsResponse
	(*timestamppb.Timestamp)(nil),            // 32: google.protobuf.Timestamp
}
var file_clients_proto_depIdxs = []int32{
	32, // 0: Assistant.CreatedAt:type_name -> google.protobuf.Timestamp
	0,  // 1: GetOneAssistantResponse.Assistant:type_name -> Assistant
	0,  // 2: GetUserAssistantsResponse.Assistants:type_name -> Assistant
	1,  // 3: GetAssistantDocumentsResponse.Documents:type_name -> Document
	2,  // 4: GetAssistantGivenAnswersResponse.GivenAnswers:type_name -> GivenAnswer
	3,  // 5: GetAssistantAppealsResponse.Appeals:type_name -> Appeal
	3,  // 6: GetUserAssistantsAppealsResponse.Appeals:type_name -> Appeal
	4,  // 7: Clients.CreateAssistant:input_type -> CreateAssistantRequest
	6,  // 8: Clients.AddDocument:input_type -> AddDocumentRequest
	8,  // 9: Clients.DeleteAssistant:input_type -> DeleteAssistantRequest
	10, // 10: Clients.DeleteDocument:input_type -> DeleteDocumentRequest
	12, // 11: Clients.GetOneAssistant:input_type -> GetOneAssistantRequest
	14, // 12: Clients.GetUserAssistants:input_type -> GetUserAssistantsRequest
	16, // 13: Clients.GetAssistantDocuments:input_type -> GetAssistantDocumentsRequest
	18, // 14: Clients.UpdateAssistant:input_type -> UpdateAssistantRequest
	20, // 15: Clients.GiveAnswer:input_type -> GiveAnswerRequest
	22, // 16: Clients.GetAssistantGivenAnswers:input_type -> GetAssistantGivenAnswersRequest
	24, // 17: Clients.DeleteGivenAnswer:input_type -> DeleteGivenAnswerRequest
	26, // 18: Clients.CreateAppeal:input_type -> CreateAppealRequest
	28, // 19: Clients.GetAssistantAppeals:input_type -> GetAssistantAppealsRequest
	30, // 20: Clients.GetUserAssistantsAppeals:input_type -> GetUserAssistantsAppealsRequest
	5,  // 21: Clients.CreateAssistant:output_type -> CreateAssistantResponse
	7,  // 22: Clients.AddDocument:output_type -> AddDocumentResponse
	9,  // 23: Clients.DeleteAssistant:output_type -> DeleteAssistantResponse
	11, // 24: Clients.DeleteDocument:output_type -> DeleteDocumentResponse
	13, // 25: Clients.GetOneAssistant:output_type -> GetOneAssistantResponse
	15, // 26: Clients.GetUserAssistants:output_type -> GetUserAssistantsResponse
	17, // 27: Clients.GetAssistantDocuments:output_type -> GetAssistantDocumentsResponse
	19, // 28: Clients.UpdateAssistant:output_type -> UpdateAssistantResponse
	21, // 29: Clients.GiveAnswer:output_type -> GiveAnswerResponse
	23, // 30: Clients.GetAssistantGivenAnswers:output_type -> GetAssistantGivenAnswersResponse
	25, // 31: Clients.DeleteGivenAnswer:output_type -> DeleteGivenAnswerResponse
	27, // 32: Clients.CreateAppeal:output_type -> CreateAppealResponse
	29, // 33: Clients.GetAssistantAppeals:output_type -> GetAssistantAppealsResponse
	31, // 34: Clients.GetUserAssistantsAppeals:output_type -> GetUserAssistantsAppealsResponse
	21, // [21:35] is the sub-list for method output_type
	7,  // [7:21] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_clients_proto_init() }
func file_clients_proto_init() {
	if File_clients_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clients_proto_rawDesc), len(file_clients_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clients_proto_goTypes,
		DependencyIndexes: file_clients_proto_depIdxs,
		MessageInfos:      file_clients_proto_msgTypes,
	}.Build()
	File_clients_proto = out.File
	file_clients_proto_goTypes = nil
	file_clients_proto_depIdxs = nil
}
