// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.1
// source: gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageToWSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=Text,proto3" json:"Text,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	AssistantId   int64                  `protobuf:"varint,3,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageToWSRequest) Reset() {
	*x = SendMessageToWSRequest{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageToWSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageToWSRequest) ProtoMessage() {}

func (x *SendMessageToWSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageToWSRequest.ProtoReflect.Descriptor instead.
func (*SendMessageToWSRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageToWSRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendMessageToWSRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SendMessageToWSRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

type SendMessageToWSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageToWSResponse) Reset() {
	*x = SendMessageToWSResponse{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageToWSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageToWSResponse) ProtoMessage() {}

func (x *SendMessageToWSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageToWSResponse.ProtoReflect.Descriptor instead.
func (*SendMessageToWSResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageToWSResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ConnectToWSRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	AssistantId    int64                  `protobuf:"varint,2,opt,name=AssistantId,proto3" json:"AssistantId,omitempty"`
	ClientPlatform string                 `protobuf:"bytes,3,opt,name=ClientPlatform,proto3" json:"ClientPlatform,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectToWSRequest) Reset() {
	*x = ConnectToWSRequest{}
	mi := &file_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectToWSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectToWSRequest) ProtoMessage() {}

func (x *ConnectToWSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectToWSRequest.ProtoReflect.Descriptor instead.
func (*ConnectToWSRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectToWSRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ConnectToWSRequest) GetAssistantId() int64 {
	if x != nil {
		return x.AssistantId
	}
	return 0
}

func (x *ConnectToWSRequest) GetClientPlatform() string {
	if x != nil {
		return x.ClientPlatform
	}
	return ""
}

type ConnectToWSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectToWSResponse) Reset() {
	*x = ConnectToWSResponse{}
	mi := &file_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectToWSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectToWSResponse) ProtoMessage() {}

func (x *ConnectToWSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectToWSResponse.ProtoReflect.Descriptor instead.
func (*ConnectToWSResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectToWSResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\"j\n" +
	"\x16SendMessageToWSRequest\x12\x12\n" +
	"\x04Text\x18\x01 \x01(\tR\x04Text\x12\x1a\n" +
	"\bClientId\x18\x02 \x01(\tR\bClientId\x12 \n" +
	"\vAssistantId\x18\x03 \x01(\x03R\vAssistantId\"1\n" +
	"\x17SendMessageToWSResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\"z\n" +
	"\x12ConnectToWSRequest\x12\x1a\n" +
	"\bClientId\x18\x01 \x01(\tR\bClientId\x12 \n" +
	"\vAssistantId\x18\x02 \x01(\x03R\vAssistantId\x12&\n" +
	"\x0eClientPlatform\x18\x03 \x01(\tR\x0eClientPlatform\"-\n" +
	"\x13ConnectToWSResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status2\x89\x01\n" +
	"\aGateway\x12D\n" +
	"\x0fSendMessageToWS\x12\x17.SendMessageToWSRequest\x1a\x18.SendMessageToWSResponse\x128\n" +
	"\vConnectToWS\x12\x13.ConnectToWSRequest\x1a\x14.ConnectToWSResponseB\tZ\a.;protob\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gateway_proto_goTypes = []any{
	(*SendMessageToWSRequest)(nil),  // 0: SendMessageToWSRequest
	(*SendMessageToWSResponse)(nil), // 1: SendMessageToWSResponse
	(*ConnectToWSRequest)(nil),      // 2: ConnectToWSRequest
	(*ConnectToWSResponse)(nil),     // 3: ConnectToWSResponse
}
var file_gateway_proto_depIdxs = []int32{
	0, // 0: Gateway.SendMessageToWS:input_type -> SendMessageToWSRequest
	2, // 1: Gateway.ConnectToWS:input_type -> ConnectToWSRequest
	1, // 2: Gateway.SendMessageToWS:output_type -> SendMessageToWSResponse
	3, // 3: Gateway.ConnectToWS:output_type -> ConnectToWSResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
